### PR TITLE
Rimworld 1.4 compatibility patch

### PR DESCRIPTION
**Pull request by ricomaster9000**
made mod compatible with Rimworld 1.4

Note - I tested everything except when one calls a squad into a map (but trading with settlements, and getting player faction caravans&tax delivery pawns I did test and that worked 100%), everything else seemed to work or the bugs caused seemed to be related to mod incompatibilities (checked debug logs to make sure).
(tested with 200 other mods, also did quick test without any mods except Harmony and this mod)

technical changes details:
copied 1.3 to 1.4
replaced usage of newborn param with DevelopmentalStage.Adult for pawn generation method calls
removed param forceInCap for incident generation method calls

### CODE REVIEW

**Comment by Danimineiro** [comment]
eb6eec2b03720860ab5cfff60f32fa82db0f8037 Why this change? Steam generally doesn't update lower to uppercase or the reverse which in experience has lead to some really annoying bugs for another modder in the past

**Comment by Danimineiro** [comment]
8f3c0e06c12a90eddd76961f0b265c68fcd26af3 I'm sorry, but this commit is just too big with the file moves
I don't have the time to look through our entire source code to identify what changes you actually made, and it's too much of a risk to just push this to out 100K subscribers without checking

**Comment by ricomaster9000** [comment]
@Danimineiro 
no problem, and sorry, it is way too big of a commit, if you suggest a specific way to do this then I will, but the changes themselves are very small required to make this mod work for Rimworld 1.4.

I could copy over directory by directory, if you throw me a bone and tell me how to handle a mass copy of files, then I will do it the way you mention, because that is what this is mostly (99.99%).

I could just do the copy over of the files (by not altering the def directory name in any way) , but then it will still be a big commit, then afterwards I can put the specific changes I had to make in a single commit (its 3/5 lines that were changes, and one word changes effectively). I will do a new branch for this however, a clean start.

If you can just throw me a link or something for a specific method I must apply to make this pr here then please do.

If you are planning to update this yourself, no problem, the subscribers can wait lol.

If you have someone else to do this update in mind, that's also okay.

(sorry I did not adhere to structure or more rational commits initially, also, I have never done such a large copy file commit before but I promise I want to do this right)

**Comment by Danimineiro** [comment]
The actual changes to the code look rather small, even though we are reworking the mod, I don't really want to change the entire structure, so I think the best way to do it is if you could make a PR with just the changes to the source code, I'd build and make Saakra role it out after having the testers play with it

**Comment by Danimineiro** [comment]
Reason I want you to make a PR like that is so you get attribution properly, if you have a link to share, please tell

**Comment by Danimineiro** [comment]
wanna do something

**Pull request closed without merging**
