### PR TITLE
- minimal implementation of military efficiency

### PR DESCRIPTION
**Pull request by TheIvoryDisaster**
Implementing military efficiency and other small improvements to auto defense

### CODE REVIEW

**Comment by TheIvoryDisaster** [comment]
Standby

**Comment by Danimineiro** [comment]
Why don't you mark these as drafts, you wouldn't have to write standby

**Comment by TheIvoryDisaster** [comment]
ready for close and merge

**Review by Danimineiro — COMMENTED** [review]
Wow that's a small and easy change

**Review by Danimineiro — APPROVED** [review]
oops forgot to press the "approve" thingy

**Pull request merged**
